apiVersion: v1
kind: ServiceAccount
metadata:
  name: url-manager
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: url-manager-role-bind-service-controller
subjects:
- kind: ServiceAccount
  name: url-manager
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-operator
spec:
  selector:
    matchLabels:
      app: url-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: url-operator
    spec:
      serviceAccountName: my-scheduler
      containers:
      - name: url-operator
        image: ty0207/url-operator:v1
        ports:
         - containerPort: 9090
